/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SellerManagement;

import business.Ecosystem;
import business.Enterprise.SellerEnterprise;
import business.Network.Network;
import business.Organization.InventoryManagementOrganization;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Gunjan
 */
public class SellerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SellerWorkAreaJPanel
     */
    private JPanel container;
    private Ecosystem system;
    private UserAccount ua;
    private InventoryManagementOrganization org;
    private SellerEnterprise sellerEnterprise;
    private Network network;
    
    public SellerWorkAreaJPanel(JPanel container,UserAccount ua,Ecosystem system, InventoryManagementOrganization org, SellerEnterprise sellerprise,Network network) {

        initComponents();
        this.container = container;
        this.org = org;
        this.system = system;
        this.ua = ua;
        this.network = network;
        this.sellerEnterprise = sellerprise;
        this.network = network;
        
        btnManageInventory.setToolTipText("Manage Inventory");
        btnPersonalInfo.setToolTipText("Personal Information");
        btnProcessOrders.setToolTipText("Process Orders");
        btnAddProducts.setToolTipText("Add Products");
        
        jLabel1.setText("<html><u>Seller Work Area</u></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageInventory = new javax.swing.JButton();
        btnPersonalInfo = new javax.swing.JButton();
        btnProcessOrders = new javax.swing.JButton();
        btnAddProducts = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), null));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Seller Work Area");

        btnManageInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventory.jpg"))); // NOI18N
        btnManageInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageInventoryActionPerformed(evt);
            }
        });

        btnPersonalInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/personalInfo.jpg"))); // NOI18N
        btnPersonalInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalInfoActionPerformed(evt);
            }
        });

        btnProcessOrders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/processOrders.jpg"))); // NOI18N
        btnProcessOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessOrdersActionPerformed(evt);
            }
        });

        btnAddProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adDProducts.jpg"))); // NOI18N
        btnAddProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProcessOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnAddProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnManageInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(btnManageInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProcessOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessOrdersActionPerformed

        ProcessOrders processOrderJPanel = new ProcessOrders(container,ua,system, org, sellerEnterprise,network);
        container.add("manageNetworkJPanel", processOrderJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnProcessOrdersActionPerformed

    private void btnManageInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageInventoryActionPerformed

        ManageInventory manageInventory = new ManageInventory(container, ua, system, org, sellerEnterprise);
        container.add("manageInventory", manageInventory);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnManageInventoryActionPerformed

    private void btnPersonalInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalInfoActionPerformed
        SellerPersonalInformationPanel jPanel = new SellerPersonalInformationPanel(container,ua, system, org, sellerEnterprise);
        container.add("SellerPersonalInformationPanel", jPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnPersonalInfoActionPerformed

    private void btnAddProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductsActionPerformed

        AddProductsJPanel addProductsJPanel = new AddProductsJPanel(container, system, ua, org, sellerEnterprise);
        container.add("AddProductsJPanel", addProductsJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnAddProductsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProducts;
    private javax.swing.JButton btnManageInventory;
    private javax.swing.JButton btnPersonalInfo;
    private javax.swing.JButton btnProcessOrders;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
