/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SystemAdmin;

import userInterface.Analysis.SelectNetworkForAnalysis;
import business.Ecosystem;
import business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Abc
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel container;
    private Ecosystem system;

    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, Ecosystem system) {
        initComponents();
        this.container = userProcessContainer;
        this.system = system;
        populateTree();
        manageNetworkJButton.setToolTipText("Manage Network");
        manageEnterpriseJButton.setToolTipText("Manage Enterprise");
        btnManageDept.setToolTipText("Manage Department");
        btnAnalyzeData.setToolTipText("Data Analysis");
        
        jLabel1.setText("<html><u>System Admin Work Area</u></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTree = new javax.swing.JTree();
        manageNetworkJButton = new javax.swing.JButton();
        manageEnterpriseJButton = new javax.swing.JButton();
        btnManageDept = new javax.swing.JButton();
        btnAnalyzeData = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));
        setAutoscrolls(true);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("System");
        JTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTree.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(JTree);

        manageNetworkJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        manageNetworkJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/network.jpg"))); // NOI18N
        manageNetworkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkJButtonActionPerformed(evt);
            }
        });

        manageEnterpriseJButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        manageEnterpriseJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enterprise.jpg"))); // NOI18N
        manageEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButtonActionPerformed(evt);
            }
        });

        btnManageDept.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnManageDept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Department.jpg"))); // NOI18N
        btnManageDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDeptActionPerformed(evt);
            }
        });

        btnAnalyzeData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAnalyzeData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/analysis.jpg"))); // NOI18N
        btnAnalyzeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyzeDataActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("System Admin Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAnalyzeData, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(manageNetworkJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(manageEnterpriseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnManageDept, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(manageNetworkJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(manageEnterpriseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnManageDept, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnalyzeData, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateTree() {

        DefaultTreeModel model = (DefaultTreeModel) JTree.getModel();

        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);

        DefaultMutableTreeNode countrynetworkNode;
        DefaultMutableTreeNode statenetworknode;
        DefaultMutableTreeNode citynetworknode;

        for (int i = 0; i < system.getNetworkDirectory().getNetworkList().size(); i++) {
            Network country = system.getNetworkDirectory().getNetworkList().get(i);
            countrynetworkNode = new DefaultMutableTreeNode(country.getName());
            networks.insert(countrynetworkNode, i);

            for (int j = 0; j < country.getNetworkDirectory().getNetworkList().size(); j++) {
                Network state = country.getNetworkDirectory().getNetworkList().get(j);
                statenetworknode = new DefaultMutableTreeNode(state.getName());
                countrynetworkNode.insert(statenetworknode, j);

                for (int k = 0; k < state.getNetworkDirectory().getNetworkList().size(); k++) {
                    Network city = state.getNetworkDirectory().getNetworkList().get(k);
                    citynetworknode = new DefaultMutableTreeNode(city.getName());
                    statenetworknode.insert(citynetworknode, k);
                }
            }
        }

        model.reload();
    }
    private void manageNetworkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkJButtonActionPerformed
        ManageNetworkJPanel manageNetworkJPanel = new ManageNetworkJPanel(container, system);
        container.add("manageNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_manageNetworkJButtonActionPerformed

    private void manageEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButtonActionPerformed

        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(container, system);
        container.add("manageEnterpriseJPanel", manageEnterpriseJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_manageEnterpriseJButtonActionPerformed

    private void btnManageDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDeptActionPerformed
        // TODO add your handling code here:
        ManageDepartmentCatalog manageDepartmentCatalog = new ManageDepartmentCatalog(container, system);
        container.add("manageDepartmentCatalog", manageDepartmentCatalog);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnManageDeptActionPerformed

    private void btnAnalyzeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyzeDataActionPerformed
        // TODO add your handling code here:
        SelectNetworkForAnalysis analysisPanel = new SelectNetworkForAnalysis(container, system);
        container.add("analysisPanel", analysisPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnAnalyzeDataActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree JTree;
    private javax.swing.JButton btnAnalyzeData;
    private javax.swing.JButton btnManageDept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageEnterpriseJButton;
    private javax.swing.JButton manageNetworkJButton;
    // End of variables declaration//GEN-END:variables
}
