/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Customer;

import business.Customer.CustomerAccount;
import business.Ecosystem;
import business.Network.Network;
import business.order.Order;
import business.order.OrderItem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gunjan
 */
public class ManageOrders extends javax.swing.JPanel {

    private JPanel container;
    private CustomerAccount custacc;
    private Ecosystem system;
    private Network network;

    /**
     * Creates new form ManageOrders
     */
    public ManageOrders(JPanel container, CustomerAccount custacc, Ecosystem system, Network network) {
        initComponents();
        this.system = system;
        this.custacc = custacc;
        this.container = container;
        this.network = network;
        populateOrdersTable();

        jLabel1.setText("<html><u>View Your Orders</u></html>");

    }

    private void populateOrdersTable() {

        DefaultTableModel ordersTable = (DefaultTableModel) tblOrder.getModel();
        ordersTable.setRowCount(0);
        for (Order order : custacc.getOrderDirectory().getOrderlist()) {
            Object row[] = new Object[4];
            row[0] = order;
            row[1] = order.getDate();
            row[2] = order.getTotalPrice();
            ordersTable.addRow(row);
        }
    }

    private void populateOrderItemList(Order order) {
        DefaultTableModel ordersTable = (DefaultTableModel) tblOrderList.getModel();
        ordersTable.setRowCount(0);
        for (OrderItem orderitem : order.getOrderItemList()) {
            Object row[] = new Object[9];
            row[0] = orderitem.getOrderItemId();
            row[1] = orderitem.getProduct();
            row[2] = orderitem.getProduct().getModelNo();
            row[3] = orderitem.getProduct().getBrand();
            row[4] = orderitem.getProductPrice();
            row[5] = orderitem.getQuantity();
            row[6] = orderitem.getTotalPrice();
            row[7] = orderitem.getStatus();
            ordersTable.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderList = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnViewOrderDts = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        tblOrderList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Item Id", "Product Name", "Model No", "Brand", "Product Price", "Quantity", "Total Price", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblOrderList);

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "OrderId", "OrderDate", "Total Price"
            }
        ));
        jScrollPane2.setViewportView(tblOrder);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("View your Orders");

        btnViewOrderDts.setText("View Order Details");
        btnViewOrderDts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrderDtsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Select the row to view the order details:");

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-arrow-icon.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(btnViewOrderDts)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewOrderDts)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewOrderDtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderDtsActionPerformed
        int selectedrow = tblOrder.getSelectedRow();
        if (selectedrow >= 0) {
            Order order = (Order) tblOrder.getValueAt(selectedrow, 0);
            if (order != null) {
                populateOrderItemList(order);
            }
        }
    }//GEN-LAST:event_btnViewOrderDtsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewOrderDts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTable tblOrderList;
    // End of variables declaration//GEN-END:variables
}
