/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Customer;

import business.Customer.CustomerAccount;
import business.Ecosystem;
import business.Enterprise.SellerEnterprise;
import business.Network.Network;
import business.Role.Role;
import business.WorkQueue.ProductOrderWorkRequest;
import business.order.Order;
import business.order.OrderItem;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gunjan
 */
public class OrderConfirmationPage extends javax.swing.JPanel {

    private JPanel container;
    private Ecosystem system;
    private Order order;
    private CustomerAccount customerAccount;
    private Network network;
    ButtonGroup bt = new ButtonGroup();

    /**
     * Creates new form OrderConfirmationPage
     */
    public OrderConfirmationPage(JPanel container, Ecosystem system, Order order, CustomerAccount customerAccount, Network network) {
        initComponents();
        this.customerAccount = customerAccount;
        this.system = system;
        this.network = network;
        this.order = order;
        this.container = container;
        populateOrderTable();
        populatePriceFields();
        groupBtn();

        jLabel8.setText("<html><u>Payment</u></html>");
    }

    public void groupBtn() {
        bt.add(rdbtnCreditCard);
        bt.add(rdbtnDebit);
        bt.add(rdbtnCod);
    }

    private void populatePriceFields() {
        double subtotal = 0.0;
        double taxtotal = 0.0;
        double totalPrice = 0.0;
        for (OrderItem orderitem : order.getOrderItemList()) {
            subtotal += orderitem.getTotalPrice();
            taxtotal += orderitem.getTax();
            totalPrice += orderitem.gettotalWithTax();
        }

        txtSubtotal.setText(String.valueOf(subtotal));
        txtsalesTax.setText(String.valueOf(taxtotal));
        txtTotal.setText(String.valueOf(totalPrice));
    }

    public void populateOrderTable() {
        DefaultTableModel orderTable = (DefaultTableModel) tblOrder.getModel();
        orderTable.setRowCount(0);
        for (OrderItem eachItem : order.getOrderItemList()) {
            Object row[] = new Object[7];
            row[0] = eachItem;
            row[1] = eachItem.getSkuHolder().seller;
            row[2] = eachItem.getProduct();
            row[3] = eachItem.getProduct().getBrand();
            row[4] = eachItem.getQuantity();
            row[5] = eachItem.getProductPrice();
            row[6] = eachItem.getTotalPrice();
            orderTable.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        txtSubtotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsalesTax = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rdbtnDebit = new javax.swing.JRadioButton();
        rdbtnCreditCard = new javax.swing.JRadioButton();
        btnDone = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        rdbtnCod = new javax.swing.JRadioButton();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Review Your Order:");

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Sr. No", "Sold By", "Product", "Brand", "Quantity", "Price", "Total Price"
            }
        ));
        jScrollPane4.setViewportView(tblOrder);

        txtSubtotal.setEditable(false);

        jLabel2.setText("Sub Total :");

        jLabel3.setText("Sales Tax:");

        txtsalesTax.setEditable(false);

        txtTotal.setEditable(false);

        jLabel4.setText("Total:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Payment Details:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Select Your Payment Method :");

        rdbtnDebit.setText("Debit Card");

        rdbtnCreditCard.setText("Credit Card");

        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Payment");

        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-arrow-icon.png"))); // NOI18N
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        rdbtnCod.setText("Cash On Delivery");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(rdbtnDebit)
                            .addComponent(rdbtnCreditCard)
                            .addComponent(btnDone)
                            .addComponent(rdbtnCod)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBack1)
                                .addGap(148, 148, 148)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(39, 39, 39)
                                    .addComponent(txtsalesTax, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(37, 37, 37)
                                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(btnBack1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtsalesTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(rdbtnDebit)
                .addGap(18, 18, 18)
                .addComponent(rdbtnCreditCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbtnCod)
                .addGap(9, 9, 9)
                .addComponent(btnDone)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed

        if ((rdbtnDebit.isSelected()) || (rdbtnCreditCard.isSelected() || rdbtnCod.isSelected())) {

            order.setDate(new Date());
            order.setTotalPrice(Double.parseDouble(txtTotal.getText()));
            order.setCustomerwhodidtheorder(customerAccount);
            customerAccount.getOrderDirectory().getOrderlist().add(order);
            network.getOrderDirectory().getOrderlist().add(order);

            for (OrderItem orderItem : order.getOrderItemList()) {
                SellerEnterprise sellerEnterprise = orderItem.getSkuHolder().seller;
                ProductOrderWorkRequest request = new ProductOrderWorkRequest(orderItem);
                request.setReceiver(sellerEnterprise.getUserAccountDirectory().getUserAccount(Role.RoleType.Admin));
                request.setSender(customerAccount);
                request.setStatus("Pending");
                sellerEnterprise.fulfillorders(request);
            }
            business.Utils.Email.send(customerAccount.getPerson().getContactDetails().getPrimaryContactNo(), customerAccount.getPerson().getContactDetails().getServiceprovider(), customerAccount.getPerson().getFirstName(), customerAccount.getPerson().getContactDetails().getEmailId());
        } else {
            JOptionPane.showMessageDialog(null, "Please select the payment method");
            return;
        }
        ConfirmationMessageJPanel confirmationMessageJPanel = new ConfirmationMessageJPanel(container, system);
        container.add("ConfirmationMessageJPanel", confirmationMessageJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnDoneActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBack1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnDone;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton rdbtnCod;
    private javax.swing.JRadioButton rdbtnCreditCard;
    private javax.swing.JRadioButton rdbtnDebit;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtsalesTax;
    // End of variables declaration//GEN-END:variables
}
